CREATE TABLE IF NOT EXISTS Guilds (
    guildID VARCHAR(100) NOT NULL,
    guildName VARCHAR(100) NOT NULL,
    guildOwnerID VARCHAR(100) NOT NULL,
    createdAt DATETIME NOT NULL,
    PRIMARY KEY (GuildID)
);