CREATE TABLE IF NOT EXISTS Guilds (
    GuildID VARCHAR(100) NOT NULL,
    GuildName VARCHAR(100) NOT NULL,
    GuildOwnerID VARCHAR(100) NOT NULL,
    CreatedAt DATETIME NOT NULL,
    PRIMARY KEY (GuildID)
);